loadbalancer:
  servers:
    server1:
      uri: http://localhost:5001
    server2:
      uri: http://localhost:5002
    server3:
      uri: http://localhost:5003
    server4:
      uri: http://localhost:5004
