loadbalancer:
  servers:
    - id: 1
      serverURI: http://host.docker.internal:5001
    - id: 2
      serverURI: http://host.docker.internal:5002
    - id: 3
      serverURI: http://host.docker.internal:5003
    - id: 4
      serverURI: http://host.docker.internal:5004
    - id: 5
      serverURI: http://host.docker.internal:5005
